name : Simple workflow

on : [push]

jobs:
  job1:
    runs-on : ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: action/setup-python@v2
      with:
        python-version: '3.8'

      -name: Say Hello
        run: echo "Hello"
  job2:
    needs: job1
    runs-on : ubuntu-lastest
    steps:
    - name: Step 2
      run: echo "job 2 en cours"